### ISSUE TITLE
JSONObject["config"]  - not found  while reading the config folder - write okay

### ISSUE THREAD

**Issue by smarty1234** [TheGamingGrunts/Thunderbolt-2#2]
I have my executable jar in build directory
I tried to created test.json under build/config
cat config/test.json
{
  "List": [
    "String 1",
    "String 2",
    "String 3"
  ],
  "herp": "derp",
  "Double": 2.5
}
--------------until this is fine----
problem starts when it tries to read it JSONObject["config"]  - not found - why ? when it can write, why it can't read ?
save works
Double works
herp works
but the next lines throws exception and program terminated - if this is not a bug and a programmer error, please advise, how to fix this ? I just tried your example and you got proper result. So, confused.

try {
        tf.save();
        System.out.println(tf.getDouble("Double"));
        System.out.println(tf.getString("herp"));
        System.out.println(tf.getStringList("List"));
       }

Exception in thread "AWT-EventQueue-0" me.projectx.thunderbolt2.org.json.JSONException: JSONObject["config"] not found.
        at me.projectx.thunderbolt2.org.json.JSONObject.get(JSONObject.java:476)
        at me.projectx.thunderbolt2.models.ThunderFile.getList(ThunderFile.java:112)
        at me.projectx.thunderbolt2.models.ThunderFile.getList(ThunderFile.java:129)
        at me.projectx.thunderbolt2.models.ThunderFile.getStringList(ThunderFile.java:133)

**Comment by TheGamingGrunts** [comment]
Sorry for responding so late. Can you post your code?

**Comment by TheGamingGrunts** [comment]
Sorry for responding so late. Try using the latest [version](http://www.spigotmc.org/resources/thunderbolt-2-lightning-fast-data-storage.3179/) and see if it fixes the issue.

**Comment by TheGamingGrunts** [comment]
This has been confirmed as fixed in the latest update.
